services:
  dbproduct:
    image: postgres:latest
    container_name: dbproduct
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Lagavi30!
      POSTGRES_DB: products
      POOLING: "true"
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
        - "5432:5432"
    user: root

    networks:
      - app-network
      
  apiproduct:
    build: 
      context: .
    container_name: apiproduct 
    ports:
      - "8000:8000"
    environment:
      ConnectionStrings__StorageContext: User ID=root;Password=Lagavi30!;Host=dbproduct;Port=5432;Database=products;
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - dbproduct
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
    
volumes:
  PGDATA: