services:
  dbproduct:
    image: postgres:latest
    container_name: dbproduct
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Lagavi30!
      POSTGRES_DB: products
      POOLING: "true"
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
        - "5432:5432"
    user: root

    networks:
      - app-network
      
  api-product:
    build: 
      context: ./
      # args:
      #   LICENSE_KEY: ${LICENSE_KEY}
    container_name: api-product
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - NEW_RELIC_LICENSE_KEY=${LICENSE_KEY}
    depends_on:
      - sqlserver-product
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
    
# volumes:
#   backend_sql_data: