name: CI/CD Storage App in Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build e Teste
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4

    - name: 2. Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'
    - name: 3. Install Dependencies
      run: dotnet restore backend/StorageProject.sln

    - name: 4. Build
      run: dotnet build backend/StorageProject.sln --no-restore
    - name: 5. Tests App
      run: dotnet test backend/StorageProject.sln --no-build
      
  build-image-to-docker:
    name: Build Image and Publish Docker Hub
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: 6. Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: 7. Buld and Push Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: gabrieldocker1/storageapp:latest
